### ISSUE TITLE
Facing issue in HOL Oracle, Exercise 1 Task 1.

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#56]
Facing issue while running the 5.northwind.oracle.seed.sql queries,
Please find the screenshot below:

1. Getting this popup while running the query.
![image](https://user-images.githubusercontent.com/45102602/148379680-0e413d98-9ee4-46f2-b030-157940abe55f.png)
I have avoided this after adding **set define off;** in starting of the queries.

2. Once the execution is completed getting this issue. 
![image](https://user-images.githubusercontent.com/45102602/148379873-1eeaa5ca-cb30-46a9-b5c3-5d5a004fe464.png)

But the tables are getting created 
![image](https://user-images.githubusercontent.com/45102602/148380338-2580f20e-9d07-43b9-b0ce-cf0467146d24.png)

**Comment by saimachi** [comment]
Hi @sumitmalik51,

Thanks for bringing this issue to our attention.

I have resolved the issue on [my fork](https://github.com/saimachi/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL) and tested the database from scratch.

Since the database is relatively easy to set up, please execute the following commands as the `system` user from SQL Developer to drop the `NW` schema.

```sql
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
DROP USER NW CASCADE;
```

Then, execute my scripts from the beginning. You should encounter no errors.

**Comment by sumitmalik51** [comment]
Hi @saimachi , does the fork resolve this issue also? https://github.com/microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL/issues/57
Thanks,

**Comment by timahenning** [comment]
The PR should resolve 56.  57 is a completely separate issue.
